spes: remove TARGET_KERNEL_CLANG_VERSION
Remove clang version declaration. This declaration forced the build system to use a specific clang version that was unavailable, causing errors such as "clang: No such file or directory. By removing this clang version declaration, the build system can now automatically detect and use the latest clang version. Also, No longer needed as the new kernel source is ready for clang 12 and higher.

Build Error:
FAILED: //vendor/blaze/build/soong:generated_kernel_includes generate (priority: 27)
Error: exited with code: 1
Output:
make: Entering directory '/home/tanvirr007/blaze_fifteen/kernel/xiaomi/sm6225'
make[1]: Entering directory '/home/tanvirr007/blaze_fifteen/out/soong/.intermediates/vendor/blaze/build/soong/generated_kernel_includes/gen'
make[1]: clang: No such file or directory
make[1]: clang: No such file or directory
make[1]: clang: No such file or directory

Signed-off-by: tanvirr007 <md.tanvirhasannijum@gmail.com>