spes: remove vendor.qti.hardware.vibrator.service
Build Error:
FAILED: //vendor/qcom/opensource/vibrator/aidl:vendor.qti.hardware.vibrator.impl generate toc vendor.qti.hardware.vibrator.impl.so
Outputs: out/soong/.intermediates/vendor/qcom/opensource/vibrator/aidl/vendor.qti.hardware.vibrator.impl/android_vendor.33_arm64_armv8-a_shared/vendor.qti.hardware.vibrator.impl.so.toc
Error: exited with code: 1
Command: echo "module vendor.qti.hardware.vibrator.impl missing dependencies: qti_vibrator_hal_defaults" && false
Output:
module vendor.qti.hardware.vibrator.impl missing dependencies: qti_vibrator_hal_defaults

Signed-off-by: Sanjivns <alshahab109@gmail.com>